<a href="https://colab.research.google.com/github/AlessandroCaforio/Python-for-ML-and-Econometrics/blob/main/Qberg_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [5]:
qberg = pd.read_csv("/content/research-09-05-2026.csv", sep=';')
qberg.head()

/tmp/ipykernel_6877/1980945124.py:1: DtypeWarning: Columns (39,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  qberg = pd.read_csv("/content/research-09-05-2026.csv", sep=';')

,Dominio,Insegna,Socio/Organizzazione,Promozione,Da,A,Categoria,Famiglia,Tipo,Marca,...,Hepa filter,Ventilato,N. porte,Ricaricabile,Classificazione Energetica,Multifunzione,Classe Energetica Europea,Funzione Lavaggio,Coperti Lavastoviglie,Connessione Wi-Fi
0,Flyer DG ITA,MEDIAWORLD,"DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET",Dyson days,2024-01-01,2024-01-10,Ped,Aspirapolvere,Scope Ricaricabili,Dyson,...,ND,NaN,NaN,Y,NaN,Versatile,NaN,N,NaN,NaN
1,Flyer DG ITA,MEDIAWORLD,"DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET",Dyson days,2024-01-01,2024-01-10,Ped,Aspirapolvere,Scope Ricaricabili,Dyson,...,N,NaN,NaN,Y,NaN,Versatile,NaN,N,NaN,NaN
2,Flyer DG ITA,UNIEURO,"CORNER UNIEURO IPER,DIRETTO UNIEURO,AFFILIATO ...",Uninews speciale Hisense,2024-01-02,2024-01-31,Ged,Lavatrici,Carica frontale,Hisense,...,NaN,NaN,NaN,NaN,NaN,NaN,A,NaN,NaN,N
3,Flyer DG ITA,UNIEURO,"CORNER UNIEURO IPER,DIRETTO UNIEURO,AFFILIATO ...",Uninews speciale Hisense,2024-01-02,2024-01-31,Ged,Frigoriferi,SBS,Hisense,...,NaN,Y,2.0,NaN,NaN,NaN,E,NaN,NaN,NaN
4,Flyer DG ITA,UNIEURO,"CORNER UNIEURO IPER,DIRETTO UNIEURO,AFFILIATO ...",Uninews speciale Hisense,2024-01-02,2024-01-31,Ged,Frigoriferi,Quattro porte,Hisense,...,NaN,Y,4.0,NaN,NaN,NaN,F,NaN,NaN,NaN

In [4]:
# Inspect the first few lines of the file to identify the structure and delimiter
with open('/content/research-09-05-2026.csv', 'r') as f:
    for i in range(5):
        print(f.readline())

Dominio;Insegna;Socio/Organizzazione;Promozione;Da;A;Categoria;Famiglia;Tipo;Marca;Modello;Pacchetti;Prezzo;"Prezzo pacchetto";"Sconto %";Pagina;Campagna;"Copertura campagna L/N";"Copertura promo L/N";"N. eventi punto vendita";Produttore;"Modello padre";Pacchetti;EAN;"Data di lancio";"Codice interno";"Modello padre";Finanziamento;"Buono Spesa/Cash Back";"Offerta Soci";"Box Branded";Sconto;"Con Prodotto In Omaggio/Incluso";Sottocosto;"Buono Spesa/Cash Back Carta Fedeltà";"Sconto/Prezzo Con Acquisto Minimo";"Sconto Carta Fedeltà";Concorso;"Accumulo punti fedeltà";;"Sottocosto Carta Fedeltà";"Errata Corrige";"Concorso Carta Fedeltà";Litri;RPM;Watt;"No Frost";"Altezza cm";Colore;"Larghezza cm";"Profondità cm";"Carico kg";Lavasciuga;Asciugatura;Sistema;"Tipo bagless";"Hepa filter";Ventilato;"N. porte";Ricaricabile;"Classificazione Energetica";Multifunzione;"Classe Energetica Europea";"Funzione Lavaggio";"Coperti Lavastoviglie";"Connessione Wi-Fi"

"Flyer DG ITA";MEDIAWORLD;"DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET";"Dyson days";2024-01-01;2024-01-10;Ped;Aspirapolvere;"Scope Ricaricabili";Dyson;"V8 MOTORHEAD 282088-01";;279;279;;1;"Dyson days";N;N;125;Dyson;"V8 MOTORHEAD 282088-01";;5025155040812;2019-06-06;;"V8 MOTORHEAD 282088-01";;;;;;;;;;;;;;;;;;;;;;;;;;;;Bagless;Dry;ND;;;Y;;Versatile;;N;;

"Flyer DG ITA";MEDIAWORLD;"DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET";"Dyson days";2024-01-01;2024-01-10;Ped;Aspirapolvere;"Scope Ricaricabili";Dyson;"GEN5 DETECT 446989-01";;799;799;;2;"Dyson days";N;N;125;Dyson;"GEN5 DETECT 446989-01";;5025155081716;2023-05-08;;"GEN5 DETECT 446989-01";;;;;;;;;;;;;;;;;;;;;;;;;;;;Bagless;Dry;N;;;Y;;Versatile;;N;;

"Flyer DG ITA";UNIEURO;"CORNER UNIEURO IPER,DIRETTO UNIEURO,AFFILIATO UNIEURO,CORNER UNIEURO CONAD";"Uninews speciale Hisense";2024-01-02;2024-01-31;Ged;Lavatrici;"Carica frontale";Hisense;WFQA1014EVJM;;449.9;449.9;;1;"Uninews speciale Hisense";N;N;386;Hisense;WFQA1014EVJM;;6901101815156;2023-02-20;;WFQA1014EVJM;"10 RATE MENSILI TAN 0% TAEG 0%";;;;;;;;;;;;;;;;;1400;;;;;;66;10.0;N;;;;;;;;;;A;;;N

"Flyer DG ITA";UNIEURO;"CORNER UNIEURO IPER,DIRETTO UNIEURO,AFFILIATO UNIEURO,CORNER UNIEURO CONAD";"Uninews speciale Hisense";2024-01-02;2024-01-31;Ged;Frigoriferi;SBS;Hisense;RS711N4ACE;;799.9;799.9;;1;"Uninews speciale Hisense";N;N;386;Hisense;RS711N4ACE;;3838782715341;2023-06-19;;RS711N4ACE;"10 RATE MENSILI TAN 0% TAEG 0%";;;;;;;;;;;;;;;;550;;;Total;179;Inox;92;;;;;;;;Y;2;;;;E;;;

In [6]:
print(qberg.describe(include = "all"))

             Dominio Insegna Socio/Organizzazione      Promozione          Da  \
count          21370   21370                21370           21370       21370
unique             1       5                   15             436         306
top     Flyer DG ITA   COMET                COMET  La casa per me  2024-02-01
freq           21370    5590                 5590            1971         346
mean             NaN     NaN                  NaN             NaN         NaN
std              NaN     NaN                  NaN             NaN         NaN
min              NaN     NaN                  NaN             NaN         NaN
25%              NaN     NaN                  NaN             NaN         NaN
50%              NaN     NaN                  NaN             NaN         NaN
75%              NaN     NaN                  NaN             NaN         NaN
max              NaN     NaN                  NaN             NaN         NaN

                 A Categoria   Famiglia             Tipo    Marca  ...  \
count        21370     21370      21370            21364    21370  ...
unique         296         2          5               21       56  ...
top     2024-01-31       Ged  Lavatrici  Carica frontale  Samsung  ...
freq           330     14790       6587             8426     3623  ...
mean           NaN       NaN        NaN              NaN      NaN  ...
std            NaN       NaN        NaN              NaN      NaN  ...
min            NaN       NaN        NaN              NaN      NaN  ...
25%            NaN       NaN        NaN              NaN      NaN  ...
50%            NaN       NaN        NaN              NaN      NaN  ...
75%            NaN       NaN        NaN              NaN      NaN  ...
max            NaN       NaN        NaN              NaN      NaN  ...

       Hepa filter  Ventilato     N. porte  Ricaricabile  \
count         6551       5351  5353.000000          6576
unique           4          3          NaN             3
top              N          Y          NaN             Y
freq          3318       3189          NaN          5221
mean           NaN        NaN     2.224547           NaN
std            NaN        NaN     0.691083           NaN
min            NaN        NaN     1.000000           NaN
25%            NaN        NaN     2.000000           NaN
50%            NaN        NaN     2.000000           NaN
75%            NaN        NaN     2.000000           NaN
max            NaN        NaN     4.000000           NaN

       Classificazione Energetica  Multifunzione Classe Energetica Europea  \
count                         601           3475                     14556
unique                          9              4                         8
top                             A      Versatile                         A
freq                          383           2914                      5597
mean                          NaN            NaN                       NaN
std                           NaN            NaN                       NaN
min                           NaN            NaN                       NaN
25%                           NaN            NaN                       NaN
50%                           NaN            NaN                       NaN
75%                           NaN            NaN                       NaN
max                           NaN            NaN                       NaN

       Funzione Lavaggio Coperti Lavastoviglie  Connessione Wi-Fi
count               6567            617.000000               9434
unique                 3                   NaN                  4
top                    N                   NaN                  N
freq                4852                   NaN               6047
mean                 NaN             13.896272                NaN
std                  NaN              0.939191                NaN
min                  NaN              6.000000                NaN
25%                  NaN             14.000000                NaN
50%                  NaN             14.000000                NaN
75%                  NaN             14.000000                NaN
max                  NaN             16.000000                NaN

[11 rows x 66 columns]

In [8]:
PROMO_FLAG_COLUMNS: tuple[str, ...] = (
    "Finanziamento",
    "BuonoSpesa/Cash Back",
    "Offerta Soci",
    "Box Branded",
    "Sconto",
    "Con Prodotto in Omaggio/Incluso",
    "Sottocosto",
    "Buono Spesa/Cash Back Carta Fedeltà",
    "Sconto/Prezzo Con Acquisto Minimo",
    "Sconto Carta Fedeltà",
    "Concorso",
    "Accumolo punti fedeltà",
    "Sottocosto Carta Fedeltà",
    "Errata Corrige",
    "Concorso Carta Fedeltà",
)

NUMERIC_COLUMNS: tuple[str, ...] =(
    "Prezzo",
    "Prezzo pacchetto",
    "Sconto %",
    "Copertura campagna L/N",
    "Copertura promo L/N",
    "N. eventi punto vendita",
    "Litri",
    "RPM",
    "Watt",
    "Altezza cm",
    "Larghezza cm",
    "Profondità cm",
    "Carico kg",
    "N. porte",
    "Coperti Lavastoviglie",
)

CATEGORY_COLUMNS: tuple[str, ...] = (
    "Dominio",
    "Insegna",
    "Categoria",
    "Famiglia",
    "Tipo",
    "Marca",
    "Produttore",
    "Colore",
    "Classe Energetica Europea",
    "Classificazione Energetica",
)

DATE_COLUMNS: tuple[str, ...] = (
    "Da",
    "A",
    "Data di lancio",
)
DATE_FORMAT: str = "%Y-%m-%d"

In [19]:
print(qberg.info())
print(qberg.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21370 entries, 0 to 21369
Data columns (total 66 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Dominio                              21370 non-null  object
 1   Insegna                              21370 non-null  object
 2   Socio/Organizzazione                 21370 non-null  object
 3   Promozione                           21370 non-null  object
 4   Da                                   21370 non-null  object
 5   A                                    21370 non-null  object
 6   Categoria                            21370 non-null  object
 7   Famiglia                             21370 non-null  object
 8   Tipo                                 21364 non-null  object
 9   Marca                                21370 non-null  object
 10  Modello                              21370 non-null  object
 11  Pacchetti                            656 non-null    float64
 12  Prezzo                               20436 non-null  float64
 13  Prezzo pacchetto                     21090 non-null  float64
 14  Sconto %                             2534 non-null   object
 15  Pagina                               21370 non-null  int64
 16  Campagna                             21370 non-null  object
 17  Copertura campagna L/N               21370 non-null  object
 18  Copertura promo L/N                  21370 non-null  object
 19  N. eventi punto vendita              21370 non-null  int64
 20  Produttore                           21370 non-null  object
 21  Modello padre                        21370 non-null  object
 22  Pacchetti.1                          656 non-null    float64
 23  EAN                                  20472 non-null  object
 24  Data di lancio                       21370 non-null  object
 25  Codice interno                       1825 non-null   object
 26  Modello padre.1                      21370 non-null  object
 27  Finanziamento                        3897 non-null   object
 28  Buono Spesa/Cash Back                1777 non-null   object
 29  Offerta Soci                         606 non-null    object
 30  Box Branded                          2289 non-null   object
 31  Sconto                               712 non-null    float64
 32  Con Prodotto In Omaggio/Incluso      1491 non-null   object
 33  Sottocosto                           536 non-null    object
 34  Buono Spesa/Cash Back Carta Fedeltà  113 non-null    object
 35  Sconto/Prezzo Con Acquisto Minimo    1680 non-null   object
 36  Sconto Carta Fedeltà                 1821 non-null   float64
 37  Concorso                             54 non-null     object
 38  Accumulo punti fedeltà               61 non-null     object
 39  Unnamed: 39                          7 non-null      object
 40  Sottocosto Carta Fedeltà             31 non-null     object
 41  Errata Corrige                       5 non-null      object
 42  Concorso Carta Fedeltà               14 non-null     object
 43  Litri                                5348 non-null   float64
 44  RPM                                  6565 non-null   float64
 45  Watt                                 3446 non-null   float64
 46  No Frost                             5336 non-null   object
 47  Altezza cm                           5348 non-null   float64
 48  Colore                               5982 non-null   object
 49  Larghezza cm                         5985 non-null   float64
 50  Profondità cm                        8701 non-null   float64
 51  Carico kg                            8796 non-null   float64
 52  Lavasciuga                           6586 non-null   object
 53  Asciugatura                          2199 non-null   object
 54  Sistema                              6509 non-null   object
 55  Tipo bagless                         6030 non-null   object
 56  Hepa filter                          6551 non-null   object
 57  Ventilato                            5351 non-null   object
 58  N. porte                             5353 non-null   float64
 59  Ricaricabile                         6576 non-null   object
 60  Classificazione Energetica           601 non-null    object
 61  Multifunzione                        3475 non-null   object
 62  Classe Energetica Europea            14556 non-null  object
 63  Funzione Lavaggio                    6567 non-null   object
 64  Coperti Lavastoviglie                617 non-null    float64
 65  Connessione Wi-Fi                    9434 non-null   object
dtypes: float64(15), int64(2), object(49)
memory usage: 10.8+ MB
None
(21370, 66)

In [21]:
print(qberg.head(3))
print(qberg.columns.tolist())

        Dominio     Insegna  \
0  Flyer DG ITA  MEDIAWORLD
1  Flyer DG ITA  MEDIAWORLD
2  Flyer DG ITA     UNIEURO

                                Socio/Organizzazione  \
0        DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET
1        DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET
2  CORNER UNIEURO IPER,DIRETTO UNIEURO,AFFILIATO ...

                 Promozione          Da           A Categoria       Famiglia  \
0                Dyson days  2024-01-01  2024-01-10       Ped  Aspirapolvere
1                Dyson days  2024-01-01  2024-01-10       Ped  Aspirapolvere
2  Uninews speciale Hisense  2024-01-02  2024-01-31       Ged      Lavatrici

                 Tipo    Marca  ... Hepa filter  Ventilato  N. porte  \
0  Scope Ricaricabili    Dyson  ...          ND        NaN       NaN
1  Scope Ricaricabili    Dyson  ...           N        NaN       NaN
2     Carica frontale  Hisense  ...         NaN        NaN       NaN

   Ricaricabile Classificazione Energetica  Multifunzione  \
0             Y                        NaN      Versatile
1             Y                        NaN      Versatile
2           NaN                        NaN            NaN

  Classe Energetica Europea Funzione Lavaggio Coperti Lavastoviglie  \
0                       NaN                 N                   NaN
1                       NaN                 N                   NaN
2                         A               NaN                   NaN

   Connessione Wi-Fi
0                NaN
1                NaN
2                  N

[3 rows x 66 columns]
['Dominio', 'Insegna', 'Socio/Organizzazione', 'Promozione', 'Da', 'A', 'Categoria', 'Famiglia', 'Tipo', 'Marca', 'Modello', 'Pacchetti', 'Prezzo', 'Prezzo pacchetto', 'Sconto %', 'Pagina', 'Campagna', 'Copertura campagna L/N', 'Copertura promo L/N', 'N. eventi punto vendita', 'Produttore', 'Modello padre', 'Pacchetti.1', 'EAN', 'Data di lancio', 'Codice interno', 'Modello padre.1', 'Finanziamento', 'Buono Spesa/Cash Back', 'Offerta Soci', 'Box Branded', 'Sconto', 'Con Prodotto In Omaggio/Incluso', 'Sottocosto', 'Buono Spesa/Cash Back Carta Fedeltà', 'Sconto/Prezzo Con Acquisto Minimo', 'Sconto Carta Fedeltà', 'Concorso', 'Accumulo punti fedeltà', 'Unnamed: 39', 'Sottocosto Carta Fedeltà', 'Errata Corrige', 'Concorso Carta Fedeltà', 'Litri', 'RPM', 'Watt', 'No Frost', 'Altezza cm', 'Colore', 'Larghezza cm', 'Profondità cm', 'Carico kg', 'Lavasciuga', 'Asciugatura', 'Sistema', 'Tipo bagless', 'Hepa filter', 'Ventilato', 'N. porte', 'Ricaricabile', 'Classificazione Energetica', 'Multifunzione', 'Classe Energetica Europea', 'Funzione Lavaggio', 'Coperti Lavastoviglie', 'Connessione Wi-Fi']

In [25]:
mask = qberg["Insegna"] == "MEDIAWORLD"
mw = qberg[mask]
### mw = qberg[qberg["Insegna"]== "MEDIAWORLD"] (This is done when we want to save space)
if mw.columns.tolist() == qberg.columns.tolist():
  print("Same columns")
else:
  print("Different columns")

Same columns

In [29]:
mw["Famiglia"].value_counts().head(5)

Famiglia
Lavatrici        1321
Frigoriferi      1076
Aspirapolvere     850
Asciugatrici      464
Lavastoviglie     175
Name: count, dtype: int64

In [31]:
## What are the 5 brand more exposed to promo in Media?
mw["Marca"].value_counts().head(5)

Marca
Samsung    793
LG         452
Haier      367
Rowenta    261
Bosch      245
Name: count, dtype: int64

In [36]:
mw = qberg[qberg['Insegna'] == 'MEDIAWORLD'].copy()
mw["Da"] = pd.to_datetime(mw["Da"])
mw["A"] = pd.to_datetime(mw["A"])
mw["Da"].dtype

dtype('<M8[ns]')

In [45]:
mw.groupby("Famiglia")["Prezzo"].mean().round(0)
print(mw.groupby("Marca")["Prezzo"].mean().sort_values().head(30))

Marca
Bissell             151.444717
OK                  242.861250
Mova Tech           243.444444
Rowenta             272.129462
Irobot              314.736842
Tineco              338.483125
Koenic              362.534167
Indesit             372.404211
Beko                422.037273
Candy               430.811643
Hoover              434.092700
Hotpoint-Ariston    450.429429
Dreame              467.981837
Ecovacs             489.327692
Dyson               532.599256
Whirlpool           536.589083
Electrolux          538.204907
Roborock            574.501000
Hisense             578.054452
Bosch               649.658589
Haier               662.371330
Xiaomi              674.000000
Miele               725.166538
AEG                 736.166604
Samsung             764.615640
LG                  813.780489
Name: Prezzo, dtype: float64

In [50]:
mw['year']= mw["Da"].dt.year
mw['Da_week']= mw["Da"].dt.isocalendar().week.astype(int)
mw['A_week'] = mw['A'].dt.isocalendar().week.astype(int)

In [57]:
mw['Finanziamento'].head(10).to_string()
print(mw['Finanziamento'].notna().head(10).to_string())
print(mw['Finanziamento'].notna().sum())
print(mw['Finanziamento'].notna().mean().round(2))

0     False
1     False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
706
0.18

In [61]:
riga = mw.iloc[0]
da = riga['Da']
a = riga['A']

lunedi_di_da =

Dominio                                                Flyer DG ITA
Insegna                                                  MEDIAWORLD
Socio/Organizzazione    DIRETTO MEDIAWORLD,CORNER MEDIAWORLD BENNET
Promozione                                               Dyson days
Da                                              2024-01-01 00:00:00
                                           ...
Connessione Wi-Fi                                               NaN
year                                                           2024
week                                                              1
Da_week                                                           1
A_week                                                            2
Name: 0, Length: 70, dtype: object